name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build with docker-compose
        run: docker compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Backend to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"
      
      - name: Deploy Frontend to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"
